services:
  vaultarr:
    image: ghcr.io/linkssy2/vaultarr:2.experimental
    container_name: vaultarr
    ports:
      - "8787:8787"
    environment:
      - LOCALAPPDATA=/config
    volumes:
      - ./config:/config
      - /path/to/games:/games
      - ./backups:/backups
    restart: unless-stopped
