services:
  vaultarr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vaultarr
    ports:
      - "8787:8787"
    environment:
      - TZ=America/Los_Angeles
      - LOCALAPPDATA=/config
      - VAULTARR_PORT=8787
    volumes:
      - ./config:/config
      - D:/Games:/games
      - D:/Vaultarr/Backups:/backups
    restart: unless-stopped
